apiVersion: v1
kind: Service
metadata:
  name: {{ include "boot.fullname" . }}
  labels:
    {{- include "boot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "boot.selectorLabels" . | nindent 4 }}
